version: '2.1'
services:
  kamailio:
    container_name: kamailio
    hostname: kamailio.valuphone.local
    build: .
    image: callforamerica/kamailio:${TAG:-latest}
    environment:
      KAMAILIO_LOG_LEVEL: info
      KAMAILIO_ENABLE_ROLES: websockets,message,presence_query,presence_sync,presence_notify_sync,registrar_sync
      KAMAILIO_AMQP_HOSTS: rabbitmq-alpha.local,rabbitmq-beta.local
      SYNC_FREESWITCH_SOURCE: dns
      SYNC_FREESWITCH_ARGS: freeswitch.local
    ports:
    - "5060-5061:5060-5061"
    - "5060:5060/udp"
    - "5064-5065:5064-5065"
    - "5064-5065:5064-5065/udp"
    - "7000-7001:7000-7001"
    - "7000:7000/udp"
    networks:
      local:
        aliases:
        - kazoo.local
    cap_add:
    - IPC_LOCK
    - NET_ADMIN
    - NET_RAW
    - NET_BROADCAST
    - SYS_NICE
    - SYS_RESOURCE
    depends_on:
      rabbitmq-alpha:
        condition: service_healthy
      rabbitmq-beta:
        condition: service_healthy
      freeswitch:
        condition: service_healthy
    networks:
      local:
        aliases:
        - kamailio.valuphone.local
  rabbitmq-alpha:
    container_name: rabbitmq-alpha
    hostname: rabbitmq-alpha.local
    environment:
      ERLANG_COOKIE: test-cookie
      RABBITMQ_USE_LONGNAME: 'true'
    image: callforamerica/rabbitmq:latest
    networks:
      local:
        aliases:
        - rabbitmq-alpha.local
  rabbitmq-beta:
    container_name: rabbitmq-beta
    hostname: rabbitmq-beta.local
    environment:
      ERLANG_COOKIE: test-cookie
      RABBITMQ_USE_LONGNAME: 'true'
    image: callforamerica/rabbitmq:latest
    networks:
      local:
        aliases:
        - rabbitmq-beta.local
  freeswitch:
    container_name: freeswitch
    hostname: freeswitch.local
    image: callforamerica/freeswitch:latest
    environment:
      FREESWITCH_DISABLE_NAT_DETECTION: 'false'
      FREESWITCH_RTP_START_PORT: 16384
      FREESWITCH_RTP_END_PORT: 16484
      ERLANG_COOKIE: test-cookie
    ports:
    - "11000:10000"
    - "11000:10000/udp"
    - "16384-16484:16384-16484/udp"
    - "8021:8021"
    - "8031:8031"
    networks:
      local:
        aliases:
        - freeswitch.local
    cap_add:
    - IPC_LOCK
    - NET_ADMIN
    - NET_RAW
    - NET_BROADCAST
    - SYS_NICE
    - SYS_RESOURCE
networks:
  local:
