version: '2.2'
services:
  kamailio:
    container_name: kamailio
    hostname: kamailio.valuphone.local
    build: images/kamailio
    image: telephoneorg/kamailio:${TAG:-latest}
    environment:
      KAMAILIO_LOG_LEVEL: info
      KAMAILIO_ENABLE_ROLES: websockets,message,presence_query,presence_notify_sync,registrar_sync
      RABBITMQ_HOSTS: rabbitmq.local
    ports:
    - "5060-5061:5060-5061"
    - "5060:5060/udp"
    - "5064-5065:5064-5065"
    - "5064-5065:5064-5065/udp"
    - "7000-7001:7000-7001"
    - "7000:7000/udp"
    cap_add:
    - IPC_LOCK
    - NET_ADMIN
    - NET_RAW
    - NET_BROADCAST
    - SYS_NICE
    - SYS_RESOURCE
    networks:
      local:
        aliases:
        - kamailio.valuphone.local
    depends_on:
      rabbitmq:
        condition: service_healthy
      freeswitch:
        condition: service_healthy
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq.local
    environment:
      ERLANG_HOSTNAME: long
      ERLANG_COOKIE: test-cookie
    image: telephoneorg/rabbitmq:latest
    networks:
      local:
        aliases:
        - rabbitmq.local
  freeswitch:
    container_name: freeswitch
    hostname: freeswitch.local
    image: telephoneorg/freeswitch:latest
    environment:
      ERLANG_HOSTNAME: long
      FREESWITCH_DISABLE_NAT_DETECTION: 'false'
      FREESWITCH_RTP_PORT_RANGE: 16384-16484
      ERLANG_COOKIE: test-cookie
    ports:
    - "11000:10000"
    - "11000:10000/udp"
    - "16384-16484:16384-16484/udp"
    - "8031:8031"
    networks:
      local:
        aliases:
        - freeswitch.local
    cap_add:
    - IPC_LOCK
    - NET_ADMIN
    - NET_RAW
    - NET_BROADCAST
    - SYS_NICE
    - SYS_RESOURCE
networks:
  local:
