apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kamailio
  labels:
    app: kamailio
    project: valuphone
    environment: production
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kamailio
        project: valuphone
        environment: production
      annotations:
        pod.beta.kubernetes.io/init-containers: |-
          [
              {
                  "name": "kubewait",
                  "image": "callforamerica/kubewait",
                  "imagePullPolicy": "IfNotPresent",
                  "args": ["rabbitmq-alpha", "rabbitmq-beta", "freeswitch"],
                  "env": [
                      {
                          "name": "NAMESPACE",
                          "valueFrom": {
                              "fieldRef": {
                                  "apiVersion": "v1",
                                  "fieldPath": "metadata.namespace"
                              }
                          }
                      }
                  ]
              }
          ]
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: saturn.valuphone.com
      containers:
      - name: kamailio
        image: callforamerica/kamailio
        imagePullPolicy: Always
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
            - NET_ADMIN
            - NET_RAW
            - NET_BROADCAST
            - SYS_NICE
            - SYS_RESOURCE
        env:
        - name: KUBE_SEARCH_DOMAINS_ADD
          valueFrom:
            configMapKeyRef:
              name: freeswitch
              key: kube.search-domains.add
        - name: KAMAILIO_AMQP_HOSTS
          valueFrom:
            configMapKeyRef:
              name: kamailio
              key: kamailio.amqp.hosts
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-creds
              key: rabbitmq.user
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-creds
              key: rabbitmq.pass
        - name: KAMAILIO_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: kamailio
              key: kamailio.log.level
        - name: KAMAILIO_LOG_COLOR
          valueFrom:
            configMapKeyRef:
              name: kamailio
              key: kamailio.log.color
        - name: KAMAILIO_ENABLE_ROLES
          valueFrom:
            configMapKeyRef:
              name: kamailio
              key: kamailio.enable-roles
        - name: SYNC_FREESWITCH_SOURCE
          valueFrom:
            configMapKeyRef:
              name: kamailio
              key: sync.freeswitch.source
        - name: SYNC_FREESWITCH_ARGS
          valueFrom:
            configMapKeyRef:
              name: kamailio
              key: sync.freeswitch.args
        - name: KAMAILIO_SHM_MEMORY
          valueFrom:
            configMapKeyRef:
              name: kamailio
              key: kamailio.shm-memory
        - name: KAMAILIO_PKG_MEMORY
          valueFrom:
            configMapKeyRef:
              name: kamailio
              key: kamailio.pkg-memory
        - name: KAMAILIO_CHILD_PROC
          valueFrom:
            configMapKeyRef:
              name: kamailio
              key: kamailio.child-proc
        ports:
        - name: sip-tcp
          containerPort: 5060
        - name: sip-udp
          protocol: UDP
          containerPort: 5060
        - name: sip-tls
          containerPort: 5061
        - name: ws-tcp
          containerPort: 5064
        - name: ws-udp
          protocol: UDP
          containerPort: 5064
        - name: wss-tcp
          containerPort: 5065
        - name: wss-udp
          protocol: UDP
          containerPort: 5065
        - name: alg-tcp
          containerPort: 7000
        - name: alg-udp
          protocol: UDP
          containerPort: 7000
        - name: alg-tls
          containerPort: 7001
        resources:
          requests:
            cpu: 2
            memory: 1Gi
          limits:
            cpu: 2
            memory: 1Gi
        readinessProbe:
          exec:
            command: ["kamctl", "monitor", "1", "|", "grep -q", "^Up"]
          initialDelaySeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          exec:
            command: ["kamctl", "monitor", "1", "|", "grep -q", "^Up"]
          initialDelaySeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 5
        volumeMounts:
        - name: volumes-ram
          mountPath: /volumes/kamailio/dbtext
        - name: tls
          mountPath: /volumes/kamailio/tls
          readOnly: false
      volumes:
      - name: volumes-ram
        emptyDir:
          medium: Memory
      - name: tls
        secret:
          secretName: wss-valuphone-com-tls
      restartPolicy: Always
