apiVersion: v1
kind: Service
metadata:
  name: kamailio
  labels:
    app: kamailio
    project: valuphone
    environment: production
spec:
  clusterIP: None
  selector:
    app: kamailio
    project: valuphone
    environment: production
  ports:
  - name: sip-tcp
    port: 5060
  - name: sip-udp
    protocol: UDP
    port: 5060
  - name: sip-tls
    port: 5061
  - name: ws-tcp
    port: 5064
  - name: ws-udp
    protocol: UDP
    port: 5064
  - name: wss-tcp
    port: 5065
  - name: wss-udp
    protocol: UDP
    port: 5065
  - name: alg-tcp
    port: 7000
  - name: alg-udp
    protocol: UDP
    port: 7000
  - name: alg-tls
    port: 7001
