kind: Pod
apiVersion: v1
metadata:
  name: <>
  labels:
    app: <>
    role: <desc>
spec:
  volumes:
    - name: erlang-cookie-secret
      secret:
        secretName: erlang-cookie
  containers:
    - name: <>
      image: callforamerica/<>
      imagePullPolicy: Always
      volumeMounts:
        - name: erlang-cookie-secret
          readOnly: true
          mountPath: /etc/secrets/erlang
      ports:
        - name: <p>
          protocol: TCP
          containerPort: 5984
    - name: epmd
      image: callforamerica/epmd
    - name: dns
      image: callforamerica/go-dnsmasq
  restartPolicy: Always