apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kamailio
  labels:
    app: kamailio
    role: sip-proxy
spec:
  replicas: 3
  selector:
    app: kamailio
    project: valuphone
  template:
    metadata:
      name: kamailio
      labels:
        app: kamailio
        project: valuphone
    spec:
      volumes:
        - name: erlang-cookie-secret
          secret:
            secretName: erlang-cookie
      containers:
        - name: kamailio
          image: callforamerica/kamailio
          imagePullPolicy: Always
          volumeMounts:
            - name: erlang-cookie-secret
              readOnly: true
              mountPath: /etc/secrets/erlang
          ports:
            - name: sip-tcp
              protocol: TCP
              containerPort: 5060
            - name: sip-udp
              protocol: UDP
              containerPort: 5060
            - name: sip-tls
              protocol: TCP
              containerPort: 5061
            - name: alg-tcp
              protocol: TCP
              containerPort: 7000
            - name: alg-udp
              protocol: UDP
              containerPort: 7000
            - name: alg-tls
              protocol: TCP
              containerPort: 7001        
        - name: dns
          image: callforamerica/go-dnsmasq
      restartPolicy: Always