apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kamailio
spec:
  template:
    metadata:
      name: kamailio
      labels:
        app: kamailio
        project: valuphone
        environment: production
    spec:
      nodeSelector: 
        kubernetes.io/hostname: plasma.valuphone.com
      hostNetwork: true
      containers:
        - name: kamailio
          image: callforamerica/kamailio
          env:
            - name: KAMAILIO_LOG_LEVEL
              value: debug
            - name: MY_WEBSOCKET_DOMAIN
              value: sip.li
          ports:
            - name: sip-tcp
              protocol: TCP
              containerPort: 5060
            - name: sip-udp
              protocol: UDP
              containerPort: 5060
            - name: alg-tcp
              protocol: TCP
              containerPort: 7000
            - name: alg-udp
              protocol: UDP
              containerPort: 7000 
          resources:
            requests:
              cpu: 2
              memory: 2G
            # limits:
            #   cpu: 
            #   memory: 
          readinessProbe:
            exec:
              command: ["kamctl", "monitor", "1", "|", "grep -q", "^Up"]
            initialDelaySeconds: 20
            timeoutSeconds: 15
          livenessProbe:
            exec:
              command: ["kamctl", "monitor", "1", "|", "grep -q", "^Up"]
            initialDelaySeconds: 60
            timeoutSeconds: 15
          imagePullPolicy: Always
      restartPolicy: Always
