kind: Service
apiVersion: v1
metadata: 
  name: kamailio
spec:
  clusterIP: None
  selector:
    app: kamailio
    project: valuphone
    environment: production
  ports:
    - name: sip-tcp
      protocol: TCP
      port: 5060
    - name: sip-udp
      protocol: UDP
      port: 5060
    - name: ws-tcp
      protocol: TCP
      port: 5064
    - name: ws-udp
      protocol: UDP
      port: 5064
    - name: alg-tcp
      protocol: TCP
      port: 7000
    - name: alg-udp
      protocol: UDP
      port: 7000
