apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kamailio
spec:
  template:
    metadata:
      name: kamailio
      labels:
        app: kamailio
    spec:
      hostNetwork: true
      volumes:
        - name: erlang-cookie-secret
          secret:
            secretName: erlang-cookie
      containers:
        - name: kamailio
          image: callforamerica/kamailio
          env:
            - name: HOST_NETWORK
              value: 'true'
          imagePullPolicy: Always
          volumeMounts:
            - name: erlang-cookie-secret
              readOnly: true
              mountPath: /etc/secrets/erlang
          ports:
            - name: sip-tcp
              protocol: TCP
              containerPort: 5060
            - name: sip-udp
              protocol: UDP
              containerPort: 5060
            - name: sip-tls
              protocol: TCP
              containerPort: 5061
            - name: alg-tcp
              protocol: TCP
              containerPort: 7000
            - name: alg-udp
              protocol: UDP
              containerPort: 7000
            - name: alg-tls
              protocol: TCP
              containerPort: 7001   
          resources:
            requests:
              cpu: 2
              memory: 2G
            # limits:
            #   cpu: 
            #   memory: 
          readinessProbe:
            exec:
              command: ["kamctl", "monitor", "1", "|", "grep -q", "^Up"]
            initialDelaySeconds: 20
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command: ["kamctl", "monitor", "1", "|", "grep -q", "^Up"]
            initialDelaySeconds: 20
            timeoutSeconds: 5
        # - name: dns
        #   image: callforamerica/go-dnsmasq
      restartPolicy: Always
