apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kamailio
spec:
  replicas: 3
  template:
    metadata:
      name: kamailio
      labels:
        app: kamailio
        project: valuphone
        environment: production
    spec:
      hostNetwork: true
      containers:
        - name: kamailio
          image: callforamerica/kamailio
          env:
            - name: KAMAILIO_LOG_LEVEL
              value: debug
            - name: MY_WEBSOCKET_DOMAIN
              value: sip.li
            - name: KAMAILIO_ENABLE_WEBSOCKETS_ROLE
              value: 'true'
            - name: KAMAILIO_ENABLE_MESSAGE_ROLE
              value: 'true'
            - name: KAMAILIO_ENABLE_PUSHER_ROLE
              value: 'true'
          ports:
            - name: sip-tcp
              protocol: TCP
              containerPort: 5060
            - name: sip-udp
              protocol: UDP
              containerPort: 5060
            - name: ws-tcp
              protocol: TCP
              containerPort: 5064
            - name: ws-udp
              protocol: UDP
              containerPort: 5064
            - name: alg-tcp
              protocol: TCP
              containerPort: 7000
            - name: alg-udp
              protocol: UDP
              containerPort: 7000
          resources:
            requests: 
              cpu: 2
              memory: 2G
            # limits:
            #   cpu:
            #   memory:
          readinessProbe:
            exec:
              command: ["kamctl", "monitor", "1", "|", "grep -q", "^Up"]
            initialDelaySeconds: 10
            timeoutSeconds: 10
          livenessProbe:
            exec:
              command: ["kamctl", "monitor", "1", "|", "grep -q", "^Up"]
            initialDelaySeconds: 30
            timeoutSeconds: 10
          imagePullPolicy: Always
      restartPolicy: Always
