apiVersion: v1
kind: ConfigMap
metadata:
  name: kamailio
  labels:
    app: kamailio
    test: 'true'
    environment: testing
data:
  kube.search-domains.add: 'true'
  kamailio.log.level: info
  kamailio.log.color: 'true'
  kamailio.amqp.hosts: rabbitmq
  kamailio.shm-memory: '128'
  kamailio.pkg-memory: '8'
  kamailio.child-proc: '8'
  kamailio.enable-roles: websockets,message,presence_query,presence_sync,presence_notify_sync,registrar_sync
  sync.freeswitch.source: kubernetes
  sync.freeswitch.args: freeswitch
---
apiVersion: v1
kind: Service
metadata:
  name: kamailio
  labels:
    app: kamailio
    test: 'true'
    environment: testing
spec:
  clusterIP: None
  selector:
    app: kamailio
    test: 'true'
    environment: testing
  ports:
  - name: sip-tcp
    port: 5060
  - name: sip-udp
    protocol: UDP
    port: 5060
  - name: sip-tls
    port: 5061
  - name: ws-tcp
    port: 5064
  - name: ws-udp
    protocol: UDP
    port: 5064
  - name: wss-tcp
    port: 5065
  - name: wss-udp
    protocol: UDP
    port: 5065
  - name: alg-tcp
    port: 7000
  - name: alg-udp
    protocol: UDP
    port: 7000
  - name: alg-tls
    port: 7001
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kamailio
  labels:
    app: kamailio
    test: 'true'
    environment: testing
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kamailio
        test: 'true'
        environment: testing
      annotations:
        pod.beta.kubernetes.io/init-containers: |-
          [
              {
                  "name": "kubewait",
                  "image": "callforamerica/kubewait",
                  "imagePullPolicy": "IfNotPresent",
                  "args": ["rabbitmq", "freeswitch"],
                  "env": [
                      {
                          "name": "NAMESPACE",
                          "valueFrom": {
                              "fieldRef": {
                                  "apiVersion": "v1",
                                  "fieldPath": "metadata.namespace"
                              }
                          }
                      }
                  ]
              }
          ]
    spec:
      hostNetwork: true
      containers:
      - name: kamailio
        image: callforamerica/kamailio:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
            - NET_ADMIN
            - NET_RAW
            - NET_BROADCAST
            - SYS_NICE
            - SYS_RESOURCE
        env:
        - name: KUBE_SEARCH_DOMAINS_ADD
          valueFrom:
            configMapKeyRef:
              name: kamailio
              key: kube.search-domains.add
        - name: KAMAILIO_AMQP_HOSTS
          valueFrom:
            configMapKeyRef:
              name: kamailio
              key: kamailio.amqp.hosts
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-creds
              key: rabbitmq.user
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-creds
              key: rabbitmq.pass
        - name: KAMAILIO_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: kamailio
              key: kamailio.log.level
        - name: KAMAILIO_LOG_COLOR
          valueFrom:
            configMapKeyRef:
              name: kamailio
              key: kamailio.log.color
        - name: KAMAILIO_ENABLE_ROLES
          valueFrom:
            configMapKeyRef:
              name: kamailio
              key: kamailio.enable-roles
        - name: SYNC_FREESWITCH_SOURCE
          valueFrom:
            configMapKeyRef:
              name: kamailio
              key: sync.freeswitch.source
        - name: SYNC_FREESWITCH_ARGS
          valueFrom:
            configMapKeyRef:
              name: kamailio
              key: sync.freeswitch.args
        - name: KAMAILIO_SHM_MEMORY
          valueFrom:
            configMapKeyRef:
              name: kamailio
              key: kamailio.shm-memory
        - name: KAMAILIO_PKG_MEMORY
          valueFrom:
            configMapKeyRef:
              name: kamailio
              key: kamailio.pkg-memory
        - name: KAMAILIO_CHILD_PROC
          valueFrom:
            configMapKeyRef:
              name: kamailio
              key: kamailio.child-proc
        ports:
        - name: sip-tcp
          containerPort: 5060
        - name: sip-udp
          protocol: UDP
          containerPort: 5060
        - name: sip-tls
          containerPort: 5061
        - name: ws-tcp
          containerPort: 5064
        - name: ws-udp
          protocol: UDP
          containerPort: 5064
        - name: wss-tcp
          containerPort: 5065
        - name: wss-udp
          protocol: UDP
          containerPort: 5065
        - name: alg-tcp
          containerPort: 7000
        - name: alg-udp
          protocol: UDP
          containerPort: 7000
        - name: alg-tls
          containerPort: 7001
        readinessProbe:
          exec:
            command: ["kamctl", "monitor", "1", "|", "grep -q", "^Up"]
          initialDelaySeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          exec:
            command: ["kamctl", "monitor", "1", "|", "grep -q", "^Up"]
          initialDelaySeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 5
        volumeMounts:
        - name: volumes-ram
          mountPath: /volumes/kamailio/dbtext
      volumes:
      - name: volumes-ram
        emptyDir:
          medium: Memory
      restartPolicy: Always
